spring:
  config:
    import:
      - application-db.yml #local db 정보
      - optional:configserver:${config.server.host:http://localhost:8888/} #configmap
  profiles:
    active: local # default - 프로필을 설정하지 않으면 local 프로필로 동작
    group:
      local: # 로컬환경에서 활성화되는 프로필 (local, hai-local, hai-db-local)
        - hai-local
        - hai-db-local
      dev: # 개발환경에서 활성화되는 프로필 (dev, hai-dev, hai-db-dev)
        - hai-dev
        - hai-db-dev
      ops: # 운영환경에서 활성화되는 프로필 (ops, hai-ops, hai-db-ops)
        - hai-ops
        - hai-db-ops
---
spring:
  config:
    activate:
      on-profile:
      - local
      - dev
      - ops
  application:
    name: s3storage-sample

server:
  port: 8080

system-info: hai

info:
  app:
    name: 게시판 서비스 (${spring.profiles.active})
    description: 게시판을 이용하거나 관리하기 위한 서비스
    version: v0.0.1

feign.circuitbreaker.enabled: true
