#jenkins JUnit 테스트 
spring:
  config:
    activate:
      on-profile:
      - jenkins-junit

junit-datasource: ENC(uFXj3dEhIhIUwDy/txxseN3Rnpw8d5xKylAcL0y+kUzhioPACKJDxl+ungR28Xy2XPTo6mk6miOYRBTPaklF8+DlhMjQBZduW3GLXU7OOIE=)
---
#H2 테스트용
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations:
        - classpath:init-data/data.sql
      schema-locations:
        - classpath:init-data/tables_new.sql
---
#5. 지식공통 DB
spring:
  config:
    activate:
      on-profile:
      - hai-db-local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test_kc
    username: sa
    password:
